### PR TITLE
Migration to Yeoman as discussed in  issue #25

### PR DESCRIPTION
**Pull request by dahagag**
I this pull request:
- Used `generator-webapp` to create a vanilla project
- Made necessary changes to migrate into the generated project structure.
- Installed required packages using bower and used `wiredep` and custom `<script>` tags for required files by the project.
- added `.mvmrc` to use NodeJS v5.10

To run the project:
1. switch to the directory and execute `nvm use` to load the correct version of NodeJS
2. `npm install -g yo bower generator-webapp`
3. `gulp serve` to open the project into browser using BrowserSync

You can also run `gulp build` to build the project into `dist` folder. Then you can run `gulp serve:dist` to run this copy.

### CODE REVIEW

**Comment by mabuelhagag** [comment]
Other things to do:
- Install `bootstrap-sass `and `jquery-ui-sass` by bower and replace the current scss files.
- Maybe remove boostrap support now as I think it isn't applied now. We can add it easily once needed.

**Comment by mabuelhagag** [comment]
@andreasbastian Should I re-factor the recent changes made in 'master' to be reflected here?

**Comment by andreasbastian** [comment]
Hey Mohammed,

Kait and I are going to be making a few more changes to meet a deadline today, so I'd hold off for now.  We haven't yet had a chance to look over your PR in detail, but let's try skyping on Thursday- will send you an email to schedule.

**Comment by mabuelhagag** [comment]
Closing this for a new PR

**Pull request closed without merging**
